# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.4"

gem "jekyll-remote-theme", "~> 0.4.3"

gem "webrick", "~> 1.9"

gem "jekyll-seo-tag", "~> 2.8"

gem "jekyll-github-metadata", "~> 2.16"

gem "jekyll-include-cache", "~> 0.2.1"

gem "jekyll-sitemap", "~> 1.4"
